repository_type: pipeline
lint:
  files_exist:
    - conf/igenomes.config
  files_unchanged:
    - assets/email_template.html
    - lib/NfcoreSchema.groovy
  pipeline_todos: False
  nextflow_config: False
